services:
  scoring_app:
    user: app
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    ports:
      - "8337:8337"
    volumes:
      - .:/app:rw
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=${DB_SERVER_VERSION}&charset=utf8mb4"
    depends_on:
      database:
        condition: service_healthy
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${DB_VERSION}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  database_data:
